---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-scheduler-publisher
data:
  PAYLOAD: job schedule
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-scheduler-publisher
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 30
          containers:
            - name: job
              image: mrflick72/job-scheduler:latest
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: job-scheduler-publisher
                - secretRef:
                    name: aws-secrets

          restartPolicy: OnFailure