version: "3.7"

services:
  job-scheduler:
    image: mrflick72/job-scheduler:latest
    environment:
      - PAYLOAD=job schedule
      - QUEUE_URL=${QUEUE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}